repos:
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        exclude: src/prompt_systematic_review/experiments/find_internal_reference_count.py
        exclude: src/prompt_systematic_review/experiments/graph_internal_references.py